# php-deployment-service.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
        - name: php-app
          image: malekkkk/phpapp:9.2
          ports:
            - containerPort: 80
          env:
            - name: DB_HOST
              value: "mysqlflexserverunique.mysql.database.azure.com"
            - name: DB_USER
              value: "mysqladmin"
            - name: DB_PASSWORD
              value: "AdminPassword123!"
            - name: DB_NAME
              value: "MedokaDB"
---
apiVersion: v1
kind: Service
metadata:
  name: php-app-service
spec:
  selector:
    app: php-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP